-- Tenant-scoped RLS on the two new automation tables, verbatim in shape from
-- 20260728100500_wf_tenant_rls.sql: Stellaforce sees everything, everyone sees
-- global rows, a client sees only its own.

alter table automation_definitions          enable row level security;
alter table automation_definition_versions  enable row level security;

do $$
declare
  tbl text;
  tables text[] := array['automation_definitions', 'automation_definition_versions'];
begin
  foreach tbl in array tables loop
    execute format($f$
      create policy "tenant_read_%1$s" on %1$I
        for select to authenticated
        using (
          public.current_profile_side() = 'stellaforce'
          or client_id is null
          or client_id = public.current_profile_client_id()
        );
    $f$, tbl);

    execute format($f$
      create policy "tenant_write_%1$s" on %1$I
        for all to authenticated
        using (
          public.current_profile_side() = 'stellaforce'
          or client_id = public.current_profile_client_id()
        )
        with check (
          public.current_profile_side() = 'stellaforce'
          or client_id = public.current_profile_client_id()
        );
    $f$, tbl);
  end loop;
end $$;

-- automation_bindings keeps the pair it inherited as `automation_rules`; the
-- previous migration renamed them and the column rename carried the expressions
-- across, so they now read `tenant_client_id`. It is deliberately NOT in the
-- loop above -- that generated policy hardcodes the column name `client_id`,
-- which no longer exists on that table. The behaviour is identical.
comment on table automation_bindings is
  'Sparse per-scope overrides of an automation definition. RLS is the standard '
  'tenant pair but written against tenant_client_id rather than client_id, so '
  'these policies are not generated by the wf_tenant_rls loop.';
